### ISSUE TITLE
Sensors not appearing in Home Assistant

### ISSUE THREAD

**Issue by mikeg-de** [mhwlng/fipha#6]
hwinfo.json is getting updated but no sensor or device is appearing in HA. Using [HASS.Agent](https://hassagent.readthedocs.io/en/latest/) auto discovery recognized the devices earlier but that approach lacks reporting of power usage. Contrary, yours offers substantially more flexibility.

log.txt
```
ERROR 2024-01-05 15:54:55,299 MoveNext - No Home Assistant Connection for Flight Instrument Panels
INFO  2024-01-05 15:54:55,311 MoveNext - fipha started
INFO  2024-01-05 15:57:17,204 OnExit - exiting
ERROR 2024-01-05 15:57:28,147 MoveNext - No Home Assistant Connection for Flight Instrument Panels
INFO  2024-01-05 15:57:28,159 MoveNext - fipha started
INFO  2024-01-05 15:57:28,215 MoveNext - HWInfo task started, polling interval 5000 ms
INFO  2024-01-05 15:57:28,236 MoveNext - HWINFO Sensors found, Writing all HWINFO Sensors to hwinfo.json
INFO  2024-01-05 15:57:28,822 MqttOnConnected - MQTT Client: Connected with result: Success
INFO  2024-01-05 16:07:38,982 OnExit - HWINFO background task ended
INFO  2024-01-05 16:07:38,983 OnExit - exiting
ERROR 2024-01-05 16:07:57,321 MoveNext - No Home Assistant Connection for Flight Instrument Panels
INFO  2024-01-05 16:07:57,334 MoveNext - fipha started
INFO  2024-01-05 16:07:57,356 MoveNext - HWInfo task started, polling interval 5000 ms
INFO  2024-01-05 16:07:57,378 MoveNext - HWINFO Sensors found, Writing all HWINFO Sensors to hwinfo.json
INFO  2024-01-05 16:07:57,415 MqttOnConnected - MQTT Client: Connected with result: Success
```

HWINFO.inc (only power draw and usage configured)
```
[Variables]
CPUPower-SensorId=0xf0000501
CPUPower-SensorInstance=0x0
CPUPower-EntryId=0x5000000

GPUPower-SensorId=0xe0002000
GPUPower-SensorInstance=0x0
GPUPower-EntryId=0x5000000

DIMM1Power-SensorId=0xf3000005
DIMM1Power-SensorInstance=0x1
DIMM1Power-PowerEntryId=0x5000003

DIMM3Power-SensorId=0xf3000005
DIMM3Power-SensorInstance=0x3
DIMM3Power-PowerEntryId=0x5000003

CPUUsage-SensorId=0xf0000300
CPUUsage-SensorInstance=0x0
CPUUsage-EntryId=0x7000021

GPUUsage-SensorId=0xe0002000
GPUUsage-SensorInstance=0x0
GPUUsage-EntryId=0x7000000

[HWINFO-Config-USAGE]
CPUUsage=CPU
GPUUsage=GPU

[HWINFO-Config-POWER]
CPUPower=CPU
GPUPower=GPU
DIMM1Power=RAM
DIMM3Power=RAM
```

mqtt.config
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <mqtt>
    <add key="mqttURI" value="192.168.1.124" />
    <add key="mqttUser" value="USER" />
    <add key="mqttPassword" value="PASS" />
    <add key="mqttPort" value="1883" />
    <add key="mqttSecure" value="False" />
    <add key="mqttPollingInterval" value="5000" />
  </mqtt>
</configuration>

```

appsettings.config
```
<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
  <add key="EnableWindowsFormsHighDpiAutoResizing" value="false" />
  <add key="haUrl" value ="" />
  <add key="haToken" value ="" />
</appSettings>

```

**Comment by mhwlng** [comment]
This information doesn't help me.
You will need to check the data using an mqtt explorer and post the results here

**Comment by mikeg-de** [comment]
I managed to find the sensors using a MQTT explorer however it seems reporting kind of stopped since I updated top HWINFO64 Pro. 

```
ERROR 2024-01-06 08:42:24,712 ReadMem - HWINFO Shared Memory Read Problem Global\HWiNFO_SENS_SM2
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, Int32 desiredAccessRights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability)
   at fipha.HWInfo.ReadMem()
ERROR 2024-01-06 08:42:24,712 MoveNext - No HWINFO Sensors Found
```

Only upon  wake from hibernation I believe one state is send to MQTT 

```
06/01/2024 06:49:34
{"device_class":"power","name":"dose power cpu","state_topic":"homeassistant/sensor/dose_power_cpu/state","unit_of_measurement":"W","value_template":"{{ value_json.value}}","unique_id":"dose_power_cpu","state_class":"measurement","availability_topic":"homeassistant/death"}

05/01/2024 22:59:28(-7.84 hours) 
{"device_class":"power","name":"dose power cpu","state_topic":"homeassistant/sensor/dose_power_cpu/state","unit_of_measurement":"W","value_template":"{{ value_json.value}}","unique_id":"dose_power_cpu","state_class":"measurement","availability_topic":"homeassistant/death"}
```

<img width="1884" alt="image" src="https://github.com/mhwlng/fipha/assets/604842/999d96f0-4b2a-4063-8b24-86162ce5a7e8">

**Comment by mhwlng** [comment]
I also use HWINFO64 pro and it works fine for me with these settings
![image](https://github.com/mhwlng/fipha/assets/1388886/4420e203-1297-4c76-9a2f-5f01b2f94a6c)

your mqtt settings look just like mine, so I'm afraid I have no idea what the problem could be ?

![image](https://github.com/mhwlng/fipha/assets/1388886/93e22c73-309b-4e99-8a4f-709f14503440)

These are my mqtt integration settings that allow mqtt discovery to work :

![image](https://github.com/mhwlng/fipha/assets/1388886/671208fe-e7db-4b69-928e-f107c6605a32)

**Comment by mikeg-de** [comment]
It seems to have resolved itself but no change was made. Reboot was done before already, though. Closing the issue.

**Comment by mikeg-de** [comment]
@mhwlng I believe I found the cause. Whilst HWINFO64 and Fipha are running in the background, the logs show that the sensors are not found. Right upon opening the sensor window, Fipha finds them and data is send to HA.

```
ERROR 2024-01-10 10:48:35,053 ReadMem - HWINFO Shared Memory Read Problem Global\HWiNFO_SENS_SM2
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, Int32 desiredAccessRights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability)
   at fipha.HWInfo.ReadMem()
ERROR 2024-01-10 10:48:35,053 MoveNext - No HWINFO Sensors Found
INFO  2024-01-10 10:48:45,102 MoveNext - HWINFO Sensors found, Writing all HWINFO Sensors to hwinfo.json
```

<img width="1102" alt="image" src="https://github.com/mhwlng/fipha/assets/604842/bda668c0-6868-4e74-82a1-0a5b51b8bb93">

**Comment by mhwlng** [comment]
This is not something I can fix in fipha.
I had the same problem when upgrading to hwinfo32 pro. 
I needed to set some checkbox in hwinfo, to auto start data collection. and then it was ok.
(I am not at home, please see hwinfo screenshot above)

**Comment by mikeg-de** [comment]
Quite strange. Without any change it is working again. Anyways, thanks for your help!
